name: Deploy to Azure VM

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NODE_VERSION: '20'
  # TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  # TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # - name: Run type check
      #   run: pnpm run type-check

      # - name: Run lint
      #   run: pnpm run lint

      # - name: Run tests
      #   run: pnpm run test

      - name: Build applications
        run: pnpm run build

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build applications
        run: pnpm run build

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            set -euo pipefail  # Strict error handling

            cd travel-assistant
            git pull origin master

            # Define the path once
            PNPM_PATH="/home/bytecrate/.nvm/versions/node/v20.19.5/bin/pnpm"

            $PNPM_PATH install
            $PNPM_PATH run build

            # Restart services with PM2
            pm2 stop all || true              # Stop all processes, '|| true' ensures script continues even if no processes exist
            pm2 delete all || true            # Delete all processes from PM2's list
            pm2 start ecosystem.config.js

            # Save PM2 process list
            pm2 save
